# config.py

# Telegram Bot token
BOT_TOKEN = "7431744705:AAGHT-QU9Cmtuxi6QB4KMgwpMjjzwiG2MLs" # "YOUR_TELEGRAM_TOKEN"

# PostgreSQL connection
POSTGRES_DB = "bot_db"
POSTGRES_USER = "bot_user"
POSTGRES_PASSWORD = "bot_pass"
POSTGRES_HOST = "localhost"
POSTGRES_PORT = 5432

# SQLAlchemy connection URI
SQLALCHEMY_DATABASE_URI = (
    f"postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}"
    f"@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}"
)

# GigaChat API key
GigaChatKey = 'ZTZjNDUxMzAtOTcxNC00MGIyLTk4MTUtNzcyYTU2ZTg4YzU5OmMwYjNhNTQ0LTQ1ZGQtNGQyYi05ZWM2LTVhM2E4ODkwNDhkYQ==' # YOUR_GIGACHAT_API_KEY
